spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(skmtJKFjFrt1eNa/Wqp4uOMhq9ect4yITR0B2eoWJsL05XvTwkIxc/etZ6dOU5k592WjmNIuoep6/vsjsOr7+PWmdTphQdb+WojNQYGgLkiO5BsIP+54mCYLnBpKdfBbuPe4odeHVLU=)
    username: ENC(ZZCJSO1j+XiHqbJgFFVm7g==)
    password: ENC(4uLCv2uRMLThzcsaiqzSHA==)


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc: ##swagger연동을 위한 설정
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
 ## IJ VM option 에 -Djasypt.encryptor.password={암호} 입력
 ## jasypt:
 ##   password: password
logging:
  level:
    org.hibernate.SQL: debug
